### ISSUE TITLE
Adding Style.(-)

### ISSUE THREAD

**Issue by zoggy** [tokenrove/tsdl-ttf#4]
I would be nice to have a `(-)` operator to remove part of a style. (I wanted to propose a patch but I'm not familiar with oasis build and it curretnly does not work because ocamlfind seems broken ☹️ ...)

**Comment by zoggy** [comment]
Something like:
```ocaml
let ( - ) st flag = Unsigned.UInt32.(logand st (lognot flag))
```

**Comment by sanette** [comment]
You may propose this here 
https://github.com/sanette/tsdl-ttf
(I'm the new maintainer)
